-- Tabela de usuários (quem faz entrada e retirada)
CREATE TABLE usuarios (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(120) NOT NULL,
  email VARCHAR2(120) NOT NULL UNIQUE
);

-- Tabela de estoque
CREATE TABLE estoque (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(120) NOT NULL,        -- Nome do item
  descricao VARCHAR2(255),            -- Detalhes adicionais do item
  categoria VARCHAR2(100),            -- Categoria do item
  quantidade NUMBER NOT NULL CHECK (quantidade >= 0), -- Controle para não ter estoque negativo
  localizacao VARCHAR2(50),           -- Onde o item está armazenado
  data_entrada TIMESTAMP NOT NULL,    -- Data de entrada no estoque
  usuarioEntrada NUMBER REFERENCES usuarios(id), -- Quem registrou a entrada
  data_retirada TIMESTAMP,            -- Quando foi retirado (última retirada)
  usuarioRetirada NUMBER REFERENCES usuarios(id) -- Quem retirou
);
ALTER TABLE estoque
ADD usuario_retirada VARCHAR2(120);
-- Índice para buscar rapidamente por nome ou categoria
CREATE INDEX idx_estoque_nome_categoria ON estoque (nome, categoria);

COMMIT;
